#|----------|
#| BINDINGS |
#|----------|

# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# menu and terminal
bind=SUPER,s,spawn,noctalia msg panel-toggle launcher
bind=ctrl+alt,t,spawn,kitty
bind=SUPER,p,spawn,noctalia msg panel-toggle session
bind=SUPER+shift,p,spawn,noctalia msg power-cycle

# misc applications
bind=SUPER,w,spawn,firefox
bind=SUPER,e,spawn,kitty yazi
bind=ctrl+shift,Escape,spawn,kitty btop

# laptop special-keys
# volume
bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute
# brightness
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down
# microphone
bind=NONE,code:124,spawn,noctalia msg mic-mute
# printscreen
bind=SUPER+shift,s,spawn,noctalia msg screenshot-region

bind=SUPER,space,spawn,noctalia msg panel-toggle control-center

# pc media key
bind=NONE,code:172,spawn,noctalia msg media toggle
bind=NONE,code:171,spawn,noctalia msg media next
bind=NONE,code:173,spawn,noctalia msg media previous

# exit
bind=SUPER,c,killclient,

# switch window focus
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down
bind=SUPER,Tab,focusmon,right

# swap window
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,togglejump,
bind=SUPER,f,togglefloating,
bind=ALT,return,togglefullscreen,
bind=SUPER,o,toggleoverlay,

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=shift+SUPER,1,tag,1,0
bind=shift+SUPER,2,tag,2,0
bind=shift+SUPER,3,tag,3,0
bind=shift+SUPER,4,tag,4,0
bind=shift+SUPER,5,tag,5,0
bind=shift+SUPER,6,tag,6,0
bind=shift+SUPER,7,tag,7,0
bind=shift+SUPER,8,tag,8,0
bind=shift+SUPER,9,tag,9,0
bind=shíft+SUPER,9,tag,9,0

bind=ctrl+SUPER,1,tagsilent,1,0
bind=ctrl+SUPER,2,tagsilent,2,0
bind=ctrl+SUPER,3,tagsilent,3,0
bind=ctrl+SUPER,4,tagsilent,4,0
bind=ctrl+SUPER,5,tagsilent,5,0
bind=ctrl+SUPER,6,tagsilent,6,0
bind=ctrl+SUPER,7,tagsilent,7,0
bind=ctrl+SUPER,8,tagsilent,8,0
bind=ctrl+SUPER,9,tagsilent,9,0
bind=ctrl+SUPER,9,tagsilent,9,0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
