source=./input.conf
source=./binds.conf
source=./theme.conf
source=./monitors.conf
source=./window_rules.conf

exec-once=noctalia
exec-once=~/.config/mango/autostart.sh

source=~/.config/mango/noctalia.conf
