# discord and music on second monitor tag 1
windowrule=tags:1,monitor:HDMI-A-2,appid:discord,isopensilent:1
windowrule=tags:1,monitor:HDMI-A-2,appid:youtube-music,isopensilent:1

# steam on primary monitor tag 2
windowrule=tags:2,monitor:DP-4,appid:steam,isopensilent:1
# steam friends list floating
windowrule=isfloating:1,title:Friends List

# firefox pip floating
windowrule=isfloating:1,isoverlay:1,isnoborder:1,title:Picture-in-Picture

# all fullscreen applications on monitor 1 have vrr enabled on fullscreen
windowrule=title: ,vrr_only_fullscreen:1
